-- =========================================================
-- DW DENGUE - POSTGRESQL
-- VERSÃO OTIMIZADA PARA CARGA FULL + 16M+ REGISTROS
-- =========================================================

DROP MATERIALIZED VIEW IF EXISTS mv_casos_evolucao_ano_uf CASCADE;
DROP MATERIALIZED VIEW IF EXISTS mv_casos_mes_uf CASCADE;
DROP MATERIALIZED VIEW IF EXISTS mv_casos_uf_ano CASCADE;
DROP TABLE IF EXISTS fato_dengue CASCADE;
DROP TABLE IF EXISTS dim_vitima CASCADE;
DROP TABLE IF EXISTS dim_tempo CASCADE;
DROP TABLE IF EXISTS dim_uf CASCADE;
DROP TABLE IF EXISTS etl_log CASCADE;

-- =========================================================
-- DIM_UF
-- =========================================================
CREATE TABLE dim_uf (
    sk_uf        SMALLSERIAL PRIMARY KEY,
    sg_uf        CHAR(2) NOT NULL,
    populacao_uf BIGINT NOT NULL,
    regiao       VARCHAR(50) NOT NULL,
    CONSTRAINT uq_dim_uf UNIQUE (sg_uf)
);

CREATE UNIQUE INDEX idx_dim_uf_sg_uf ON dim_uf (sg_uf);

-- =========================================================
-- DIM_TEMPO
-- =========================================================
CREATE TABLE dim_tempo (
    sk_tempo         BIGSERIAL PRIMARY KEY,
    data_completa    DATE NOT NULL,
    data_formatada   VARCHAR(10) NOT NULL,
    ano              SMALLINT NOT NULL,
    semestre         SMALLINT NOT NULL,
    trimestre        SMALLINT NOT NULL,
    mes              SMALLINT NOT NULL,
    nome_mes         VARCHAR(20) NOT NULL,
    dia              SMALLINT NOT NULL,
    dia_semana_num   SMALLINT NOT NULL,
    nome_dia_semana  VARCHAR(20) NOT NULL,
    semana_ano       SMALLINT NOT NULL,
    fim_de_semana    BOOLEAN NOT NULL,
    CONSTRAINT uq_dim_tempo UNIQUE (data_completa)
);

CREATE UNIQUE INDEX idx_dim_tempo_data ON dim_tempo (data_completa);
CREATE INDEX idx_dim_tempo_ano_mes ON dim_tempo (ano, mes);

-- =========================================================
-- DIM_VITIMA
-- =========================================================
CREATE TABLE dim_vitima (
    sk_vitima          BIGSERIAL PRIMARY KEY,
    cs_sexo            VARCHAR(2) NOT NULL DEFAULT 'NI',
    cs_gestant         SMALLINT NOT NULL DEFAULT 0,
    diabetes           SMALLINT NOT NULL DEFAULT 0,
    hematolog          SMALLINT NOT NULL DEFAULT 0,
    hepatopati         SMALLINT NOT NULL DEFAULT 0,
    renal              SMALLINT NOT NULL DEFAULT 0,
    hipertensa         SMALLINT NOT NULL DEFAULT 0,
    auto_imune         SMALLINT NOT NULL DEFAULT 0,
    possui_comorbidade SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_dim_vitima UNIQUE (
        cs_sexo,
        cs_gestant,
        diabetes,
        hematolog,
        hepatopati,
        renal,
        hipertensa,
        auto_imune,
        possui_comorbidade
    ),
    CONSTRAINT chk_dim_vitima_cs_gestant CHECK (cs_gestant IN (0,1,2,9)),
    CONSTRAINT chk_dim_vitima_diabetes CHECK (diabetes IN (0,1,2,9)),
    CONSTRAINT chk_dim_vitima_hematolog CHECK (hematolog IN (0,1,2,9)),
    CONSTRAINT chk_dim_vitima_hepatopati CHECK (hepatopati IN (0,1,2,9)),
    CONSTRAINT chk_dim_vitima_renal CHECK (renal IN (0,1,2,9)),
    CONSTRAINT chk_dim_vitima_hipertensa CHECK (hipertensa IN (0,1,2,9)),
    CONSTRAINT chk_dim_vitima_auto_imune CHECK (auto_imune IN (0,1,2,9)),
    CONSTRAINT chk_dim_vitima_possui_comorbidade CHECK (possui_comorbidade IN (0,1))
);

select * from dim_vitima

CREATE UNIQUE INDEX idx_dim_vitima_natural
    ON dim_vitima (
        cs_sexo,
        cs_gestant,
        diabetes,
        hematolog,
        hepatopati,
        renal,
        hipertensa,
        auto_imune,
        possui_comorbidade
    );

-- =========================================================
-- FATO_DENGUE
-- 1 linha = 1 caso/notificação
-- Otimizações:
-- - sem PK composta pesada para acelerar carga
-- - particionamento por ano
-- - tipos enxutos
-- - apenas índices realmente úteis
-- =========================================================
CREATE TABLE fato_dengue (
    id_caso          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nu_ano           INTEGER NOT NULL,

    sk_uf            BIGINT NOT NULL,
    sk_tempo_notific BIGINT,
    sk_tempo_invest  BIGINT,
    sk_tempo_encerra BIGINT,
    sk_vitima        BIGINT NOT NULL,

    ano_nasc         INTEGER,

    mialgia          SMALLINT NOT NULL DEFAULT 0,
    cefaleia         SMALLINT NOT NULL DEFAULT 0,
    exantema         SMALLINT NOT NULL DEFAULT 0,
    vomito           SMALLINT NOT NULL DEFAULT 0,
    nausea           SMALLINT NOT NULL DEFAULT 0,
    dor_costas       SMALLINT NOT NULL DEFAULT 0,
    conjuntvit       SMALLINT NOT NULL DEFAULT 0,
    artrite          SMALLINT NOT NULL DEFAULT 0,
    artralgia        SMALLINT NOT NULL DEFAULT 0,
    petequia_n       SMALLINT NOT NULL DEFAULT 0,
    leucopenia       SMALLINT NOT NULL DEFAULT 0,
    laco             SMALLINT NOT NULL DEFAULT 0,
    dor_retro        SMALLINT NOT NULL DEFAULT 0,

    alrm_hipot       SMALLINT NOT NULL DEFAULT 0,
    alrm_plaq        SMALLINT NOT NULL DEFAULT 0,
    alrm_vom         SMALLINT NOT NULL DEFAULT 0,
    alrm_sang        SMALLINT NOT NULL DEFAULT 0,
    alrm_hemat       SMALLINT NOT NULL DEFAULT 0,
    alrm_abdom       SMALLINT NOT NULL DEFAULT 0,
    alrm_letar       SMALLINT NOT NULL DEFAULT 0,
    alrm_hepat       SMALLINT NOT NULL DEFAULT 0,
    alrm_liq         SMALLINT NOT NULL DEFAULT 0,

    grav_pulso       SMALLINT NOT NULL DEFAULT 0,
    grav_conv        SMALLINT NOT NULL DEFAULT 0,
    grav_ench        SMALLINT NOT NULL DEFAULT 0,
    grav_insuf       SMALLINT NOT NULL DEFAULT 0,
    grav_taqui       SMALLINT NOT NULL DEFAULT 0,
    grav_extre       SMALLINT NOT NULL DEFAULT 0,
    grav_hipot       SMALLINT NOT NULL DEFAULT 0,
    grav_hemat       SMALLINT NOT NULL DEFAULT 0,
    grav_melen       SMALLINT NOT NULL DEFAULT 0,
    grav_metro       SMALLINT NOT NULL DEFAULT 0,
    grav_sang        SMALLINT NOT NULL DEFAULT 0,
    grav_ast         SMALLINT NOT NULL DEFAULT 0,
    grav_mioc        SMALLINT NOT NULL DEFAULT 0,
    grav_consc       SMALLINT NOT NULL DEFAULT 0,
    grav_orgao       SMALLINT NOT NULL DEFAULT 0,

    hospitaliz       SMALLINT NOT NULL DEFAULT 0,
    evolucao         SMALLINT NOT NULL DEFAULT 0,
    qtd_casos        INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT fk_fato_dengue_uf FOREIGN KEY (sk_uf) REFERENCES dim_uf(sk_uf),
    CONSTRAINT fk_fato_dengue_tempo_notific FOREIGN KEY (sk_tempo_notific) REFERENCES dim_tempo(sk_tempo),
    CONSTRAINT fk_fato_dengue_tempo_invest FOREIGN KEY (sk_tempo_invest) REFERENCES dim_tempo(sk_tempo),
    CONSTRAINT fk_fato_dengue_tempo_encerra FOREIGN KEY (sk_tempo_encerra) REFERENCES dim_tempo(sk_tempo),
    CONSTRAINT fk_fato_dengue_vitima FOREIGN KEY (sk_vitima) REFERENCES dim_vitima(sk_vitima),
    CONSTRAINT chk_fato_dengue_nu_ano CHECK (nu_ano BETWEEN 1900 AND 2100),
    CONSTRAINT chk_fato_dengue_ano_nasc CHECK (ano_nasc IS NULL OR ano_nasc BETWEEN 1900 AND 2100),
    CONSTRAINT chk_fato_dengue_qtd_casos CHECK (qtd_casos >= 1)
) PARTITION BY LIST (nu_ano);

CREATE TABLE fato_dengue_2019 PARTITION OF fato_dengue FOR VALUES IN (2019);
CREATE TABLE fato_dengue_2020 PARTITION OF fato_dengue FOR VALUES IN (2020);
CREATE TABLE fato_dengue_2021 PARTITION OF fato_dengue FOR VALUES IN (2021);
CREATE TABLE fato_dengue_2022 PARTITION OF fato_dengue FOR VALUES IN (2022);
CREATE TABLE fato_dengue_2023 PARTITION OF fato_dengue FOR VALUES IN (2023);
CREATE TABLE fato_dengue_2024 PARTITION OF fato_dengue FOR VALUES IN (2024);
CREATE TABLE fato_dengue_2025 PARTITION OF fato_dengue FOR VALUES IN (2025);
CREATE TABLE fato_dengue_2026 PARTITION OF fato_dengue FOR VALUES IN (2026);
CREATE TABLE fato_dengue_outros PARTITION OF fato_dengue DEFAULT;

-- Índices mínimos e úteis para DW / Power BI
CREATE INDEX idx_fato_dengue_sk_uf ON fato_dengue (sk_uf);
CREATE INDEX idx_fato_dengue_sk_tempo_notific ON fato_dengue (sk_tempo_notific);
CREATE INDEX idx_fato_dengue_sk_vitima ON fato_dengue (sk_vitima);
CREATE INDEX idx_fato_dengue_evolucao ON fato_dengue (evolucao);
CREATE INDEX idx_fato_dengue_uf_tempo_notific ON fato_dengue (sk_uf, sk_tempo_notific);

-- =========================================================
-- ETL_LOG
-- =========================================================
CREATE TABLE etl_log (
    id SERIAL PRIMARY KEY,
    etapa VARCHAR(100),
    registros_processados BIGINT,
    inicio TIMESTAMP,
    fim TIMESTAMP,
    duracao_segundos NUMERIC(10,2),
    status VARCHAR(20),
    erro TEXT
);

COMMENT ON TABLE dim_uf IS 'Dimensão territorial por UF, com população e região.';
COMMENT ON TABLE dim_tempo IS 'Dimensão calendário reutilizada para dt_notific, dt_invest e dt_encerra.';
COMMENT ON TABLE dim_vitima IS 'Dimensão descritiva da vítima sem ano_nasc e sem faixa_etaria.';
COMMENT ON TABLE fato_dengue IS 'Tabela fato no grão de 1 linha por caso/notificação de dengue.';
COMMENT ON COLUMN fato_dengue.qtd_casos IS 'Medida padrão da fato. Valor fixo 1 para contagem de casos.';
COMMENT ON COLUMN fato_dengue.evolucao IS 'Código padronizado de evolução do caso mantido a partir da base tratada.';
COMMENT ON COLUMN dim_vitima.possui_comorbidade IS 'Flag derivada para facilitar análises de negócio.';

-- =========================================================
-- AGREGAÇÕES PARA CONSUMO ANALÍTICO / POWER BI
-- =========================================================


CREATE OR REPLACE VIEW vw_dengue_analitica AS
SELECT
    -- fato
    f.id_caso,
    f.nu_ano,
    f.ano_nasc,
    f.evolucao,
    f.hospitaliz,
    f.qtd_casos,
    f.mialgia,
    f.cefaleia,
    f.exantema,
    f.vomito,
    f.nausea,
    f.dor_costas,
    f.conjuntvit,
    f.artrite,
    f.artralgia,
    f.petequia_n,
    f.leucopenia,
    f.laco,
    f.dor_retro,
    f.alrm_hipot,
    f.alrm_plaq,
    f.alrm_vom,
    f.alrm_sang,
    f.alrm_hemat,
    f.alrm_abdom,
    f.alrm_letar,
    f.alrm_hepat,
    f.alrm_liq,
    f.grav_pulso,
    f.grav_conv,
    f.grav_ench,
    f.grav_insuf,
    f.grav_taqui,
    f.grav_extre,
    f.grav_hipot,
    f.grav_hemat,
    f.grav_melen,
    f.grav_metro,
    f.grav_sang,
    f.grav_ast,
    f.grav_mioc,
    f.grav_consc,
    f.grav_orgao,
    -- dim_uf
    u.sg_uf,
    u.regiao,
    u.populacao_uf,
    -- dim_tempo (notificação)
    t.data_completa     AS dt_notificacao,
    t.ano               AS ano_notificacao,
    t.semestre          AS semestre_notificacao,
    t.trimestre         AS trimestre_notificacao,
    t.mes               AS mes_notificacao,
    t.mes               AS mes_num,
    t.nome_mes          AS nome_mes_notificacao,
    t.dia               AS dia_notificacao,
    t.dia_semana_num    AS dia_semana_num_notificacao,
    t.nome_dia_semana   AS nome_dia_semana_notificacao,
    t.semana_ano        AS semana_ano_notificacao,
    t.fim_de_semana     AS fim_de_semana_notificacao,
    -- dim_vitima
    v.cs_sexo,
    v.cs_gestant,
    v.diabetes,
    v.hematolog,
    v.hepatopati,
    v.renal,
    v.hipertensa,
    v.auto_imune,
    v.possui_comorbidade,
    -- idade derivada
    CASE
        WHEN f.ano_nasc IS NOT NULL
         AND f.ano_nasc BETWEEN 1900 AND f.nu_ano
        THEN f.nu_ano - f.ano_nasc
        ELSE NULL
    END AS idade,
    CASE
        WHEN f.ano_nasc IS NULL                          THEN 'Não informado'
        WHEN f.ano_nasc < 1900 OR f.ano_nasc > f.nu_ano THEN 'Não informado'
        WHEN (f.nu_ano - f.ano_nasc) < 10               THEN '0-9'
        WHEN (f.nu_ano - f.ano_nasc) < 20               THEN '10-19'
        WHEN (f.nu_ano - f.ano_nasc) < 30               THEN '20-29'
        WHEN (f.nu_ano - f.ano_nasc) < 40               THEN '30-39'
        WHEN (f.nu_ano - f.ano_nasc) < 50               THEN '40-49'
        WHEN (f.nu_ano - f.ano_nasc) < 60               THEN '50-59'
        WHEN (f.nu_ano - f.ano_nasc) < 70               THEN '60-69'
        ELSE '70+'
    END AS faixa_etaria,
    -- total de casos (padrão DW)
    1 AS total_casos,
    -- abreviação do mês
    CASE t.mes
        WHEN 1  THEN 'Jan'
        WHEN 2  THEN 'Fev'
        WHEN 3  THEN 'Mar'
        WHEN 4  THEN 'Abr'
        WHEN 5  THEN 'Mai'
        WHEN 6  THEN 'Jun'
        WHEN 7  THEN 'Jul'
        WHEN 8  THEN 'Ago'
        WHEN 9  THEN 'Set'
        WHEN 10 THEN 'Out'
        WHEN 11 THEN 'Nov'
        WHEN 12 THEN 'Dez'
    END AS mes_abrev,
    -- ordenação da faixa etária (nova coluna adicionada ao final)
    CASE
        WHEN f.ano_nasc IS NULL                          THEN 99
        WHEN f.ano_nasc < 1900 OR f.ano_nasc > f.nu_ano THEN 99
        WHEN (f.nu_ano - f.ano_nasc) < 10               THEN 1
        WHEN (f.nu_ano - f.ano_nasc) < 20               THEN 2
        WHEN (f.nu_ano - f.ano_nasc) < 30               THEN 3
        WHEN (f.nu_ano - f.ano_nasc) < 40               THEN 4
        WHEN (f.nu_ano - f.ano_nasc) < 50               THEN 5
        WHEN (f.nu_ano - f.ano_nasc) < 60               THEN 6
        WHEN (f.nu_ano - f.ano_nasc) < 70               THEN 7
        ELSE                                                  8
    END AS ordem_faixa_etaria
FROM fato_dengue f
LEFT JOIN dim_uf u
    ON f.sk_uf = u.sk_uf
LEFT JOIN dim_tempo t
    ON f.sk_tempo_notific = t.sk_tempo
LEFT JOIN dim_vitima v
    ON f.sk_vitima = v.sk_vitima;


CREATE OR REPLACE VIEW vw_sintomas_frequencia AS
WITH sintomas_base AS (
    SELECT evolucao, 'mialgia' AS sintoma, mialgia AS presente FROM fato_dengue
    UNION ALL
    SELECT evolucao, 'cefaleia', cefaleia FROM fato_dengue
    UNION ALL
    SELECT evolucao, 'exantema', exantema FROM fato_dengue
    UNION ALL
    SELECT evolucao, 'vomito', vomito FROM fato_dengue
    UNION ALL
    SELECT evolucao, 'nausea', nausea FROM fato_dengue
    UNION ALL
    SELECT evolucao, 'dor_costas', dor_costas FROM fato_dengue
    UNION ALL
    SELECT evolucao, 'conjuntvit', conjuntvit FROM fato_dengue
    UNION ALL
    SELECT evolucao, 'artrite', artrite FROM fato_dengue
    UNION ALL
    SELECT evolucao, 'artralgia', artralgia FROM fato_dengue
    UNION ALL
    SELECT evolucao, 'petequia_n', petequia_n FROM fato_dengue
    UNION ALL
    SELECT evolucao, 'leucopenia', leucopenia FROM fato_dengue
    UNION ALL
    SELECT evolucao, 'laco', laco FROM fato_dengue
    UNION ALL
    SELECT evolucao, 'dor_retro', dor_retro FROM fato_dengue
)


SELECT
    sintoma,
    COUNT(*) FILTER (WHERE presente = 1) AS total_casos,
    SUM(CASE WHEN presente = 1 AND evolucao = 2 THEN 1 ELSE 0 END) AS total_obitos,
    ROUND(
        SUM(CASE WHEN presente = 1 AND evolucao = 2 THEN 1 ELSE 0 END)::numeric
        / NULLIF(COUNT(*) FILTER (WHERE presente = 1), 0),
        6
    ) AS taxa_letalidade
FROM sintomas_base
GROUP BY sintoma;

CREATE OR REPLACE VIEW vw_sintomas_faixa_etaria AS
WITH sintomas_base AS (
    SELECT
        CASE
            WHEN f.ano_nasc IS NULL THEN 'Não informado'
            WHEN f.ano_nasc < 1900 OR f.ano_nasc > f.nu_ano THEN 'Não informado'
            WHEN (f.nu_ano - f.ano_nasc) < 10 THEN '0-9'
            WHEN (f.nu_ano - f.ano_nasc) < 20 THEN '10-19'
            WHEN (f.nu_ano - f.ano_nasc) < 30 THEN '20-29'
            WHEN (f.nu_ano - f.ano_nasc) < 40 THEN '30-39'
            WHEN (f.nu_ano - f.ano_nasc) < 50 THEN '40-49'
            WHEN (f.nu_ano - f.ano_nasc) < 60 THEN '50-59'
            WHEN (f.nu_ano - f.ano_nasc) < 70 THEN '60-69'
            ELSE '70+'
        END AS faixa_etaria,
        f.evolucao,
        'mialgia' AS sintoma,
        f.mialgia AS presente
    FROM fato_dengue f

    UNION ALL
    SELECT
        CASE
            WHEN f.ano_nasc IS NULL THEN 'Não informado'
            WHEN f.ano_nasc < 1900 OR f.ano_nasc > f.nu_ano THEN 'Não informado'
            WHEN (f.nu_ano - f.ano_nasc) < 10 THEN '0-9'
            WHEN (f.nu_ano - f.ano_nasc) < 20 THEN '10-19'
            WHEN (f.nu_ano - f.ano_nasc) < 30 THEN '20-29'
            WHEN (f.nu_ano - f.ano_nasc) < 40 THEN '30-39'
            WHEN (f.nu_ano - f.ano_nasc) < 50 THEN '40-49'
            WHEN (f.nu_ano - f.ano_nasc) < 60 THEN '50-59'
            WHEN (f.nu_ano - f.ano_nasc) < 70 THEN '60-69'
            ELSE '70+'
        END,
        f.evolucao, 'cefaleia', f.cefaleia
    FROM fato_dengue f

    UNION ALL
    SELECT
        CASE
            WHEN f.ano_nasc IS NULL THEN 'Não informado'
            WHEN f.ano_nasc < 1900 OR f.ano_nasc > f.nu_ano THEN 'Não informado'
            WHEN (f.nu_ano - f.ano_nasc) < 10 THEN '0-9'
            WHEN (f.nu_ano - f.ano_nasc) < 20 THEN '10-19'
            WHEN (f.nu_ano - f.ano_nasc) < 30 THEN '20-29'
            WHEN (f.nu_ano - f.ano_nasc) < 40 THEN '30-39'
            WHEN (f.nu_ano - f.ano_nasc) < 50 THEN '40-49'
            WHEN (f.nu_ano - f.ano_nasc) < 60 THEN '50-59'
            WHEN (f.nu_ano - f.ano_nasc) < 70 THEN '60-69'
            ELSE '70+'
        END,
        f.evolucao, 'exantema', f.exantema
    FROM fato_dengue f

    UNION ALL
    SELECT
        CASE
            WHEN f.ano_nasc IS NULL THEN 'Não informado'
            WHEN f.ano_nasc < 1900 OR f.ano_nasc > f.nu_ano THEN 'Não informado'
            WHEN (f.nu_ano - f.ano_nasc) < 10 THEN '0-9'
            WHEN (f.nu_ano - f.ano_nasc) < 20 THEN '10-19'
            WHEN (f.nu_ano - f.ano_nasc) < 30 THEN '20-29'
            WHEN (f.nu_ano - f.ano_nasc) < 40 THEN '30-39'
            WHEN (f.nu_ano - f.ano_nasc) < 50 THEN '40-49'
            WHEN (f.nu_ano - f.ano_nasc) < 60 THEN '50-59'
            WHEN (f.nu_ano - f.ano_nasc) < 70 THEN '60-69'
            ELSE '70+'
        END,
        f.evolucao, 'vomito', f.vomito
    FROM fato_dengue f

    UNION ALL
    SELECT
        CASE
            WHEN f.ano_nasc IS NULL THEN 'Não informado'
            WHEN f.ano_nasc < 1900 OR f.ano_nasc > f.nu_ano THEN 'Não informado'
            WHEN (f.nu_ano - f.ano_nasc) < 10 THEN '0-9'
            WHEN (f.nu_ano - f.ano_nasc) < 20 THEN '10-19'
            WHEN (f.nu_ano - f.ano_nasc) < 30 THEN '20-29'
            WHEN (f.nu_ano - f.ano_nasc) < 40 THEN '30-39'
            WHEN (f.nu_ano - f.ano_nasc) < 50 THEN '40-49'
            WHEN (f.nu_ano - f.ano_nasc) < 60 THEN '50-59'
            WHEN (f.nu_ano - f.ano_nasc) < 70 THEN '60-69'
            ELSE '70+'
        END,
        f.evolucao, 'nausea', f.nausea
    FROM fato_dengue f

    UNION ALL
    SELECT
        CASE
            WHEN f.ano_nasc IS NULL THEN 'Não informado'
            WHEN f.ano_nasc < 1900 OR f.ano_nasc > f.nu_ano THEN 'Não informado'
            WHEN (f.nu_ano - f.ano_nasc) < 10 THEN '0-9'
            WHEN (f.nu_ano - f.ano_nasc) < 20 THEN '10-19'
            WHEN (f.nu_ano - f.ano_nasc) < 30 THEN '20-29'
            WHEN (f.nu_ano - f.ano_nasc) < 40 THEN '30-39'
            WHEN (f.nu_ano - f.ano_nasc) < 50 THEN '40-49'
            WHEN (f.nu_ano - f.ano_nasc) < 60 THEN '50-59'
            WHEN (f.nu_ano - f.ano_nasc) < 70 THEN '60-69'
            ELSE '70+'
        END,
        f.evolucao, 'dor_costas', f.dor_costas
    FROM fato_dengue f

    UNION ALL
    SELECT
        CASE
            WHEN f.ano_nasc IS NULL THEN 'Não informado'
            WHEN f.ano_nasc < 1900 OR f.ano_nasc > f.nu_ano THEN 'Não informado'
            WHEN (f.nu_ano - f.ano_nasc) < 10 THEN '0-9'
            WHEN (f.nu_ano - f.ano_nasc) < 20 THEN '10-19'
            WHEN (f.nu_ano - f.ano_nasc) < 30 THEN '20-29'
            WHEN (f.nu_ano - f.ano_nasc) < 40 THEN '30-39'
            WHEN (f.nu_ano - f.ano_nasc) < 50 THEN '40-49'
            WHEN (f.nu_ano - f.ano_nasc) < 60 THEN '50-59'
            WHEN (f.nu_ano - f.ano_nasc) < 70 THEN '60-69'
            ELSE '70+'
        END,
        f.evolucao, 'conjuntvit', f.conjuntvit
    FROM fato_dengue f

    UNION ALL
    SELECT
        CASE
            WHEN f.ano_nasc IS NULL THEN 'Não informado'
            WHEN f.ano_nasc < 1900 OR f.ano_nasc > f.nu_ano THEN 'Não informado'
            WHEN (f.nu_ano - f.ano_nasc) < 10 THEN '0-9'
            WHEN (f.nu_ano - f.ano_nasc) < 20 THEN '10-19'
            WHEN (f.nu_ano - f.ano_nasc) < 30 THEN '20-29'
            WHEN (f.nu_ano - f.ano_nasc) < 40 THEN '30-39'
            WHEN (f.nu_ano - f.ano_nasc) < 50 THEN '40-49'
            WHEN (f.nu_ano - f.ano_nasc) < 60 THEN '50-59'
            WHEN (f.nu_ano - f.ano_nasc) < 70 THEN '60-69'
            ELSE '70+'
        END,
        f.evolucao, 'artrite', f.artrite
    FROM fato_dengue f

    UNION ALL
    SELECT
        CASE
            WHEN f.ano_nasc IS NULL THEN 'Não informado'
            WHEN f.ano_nasc < 1900 OR f.ano_nasc > f.nu_ano THEN 'Não informado'
            WHEN (f.nu_ano - f.ano_nasc) < 10 THEN '0-9'
            WHEN (f.nu_ano - f.ano_nasc) < 20 THEN '10-19'
            WHEN (f.nu_ano - f.ano_nasc) < 30 THEN '20-29'
            WHEN (f.nu_ano - f.ano_nasc) < 40 THEN '30-39'
            WHEN (f.nu_ano - f.ano_nasc) < 50 THEN '40-49'
            WHEN (f.nu_ano - f.ano_nasc) < 60 THEN '50-59'
            WHEN (f.nu_ano - f.ano_nasc) < 70 THEN '60-69'
            ELSE '70+'
        END,
        f.evolucao, 'artralgia', f.artralgia
    FROM fato_dengue f

    UNION ALL
    SELECT
        CASE
            WHEN f.ano_nasc IS NULL THEN 'Não informado'
            WHEN f.ano_nasc < 1900 OR f.ano_nasc > f.nu_ano THEN 'Não informado'
            WHEN (f.nu_ano - f.ano_nasc) < 10 THEN '0-9'
            WHEN (f.nu_ano - f.ano_nasc) < 20 THEN '10-19'
            WHEN (f.nu_ano - f.ano_nasc) < 30 THEN '20-29'
            WHEN (f.nu_ano - f.ano_nasc) < 40 THEN '30-39'
            WHEN (f.nu_ano - f.ano_nasc) < 50 THEN '40-49'
            WHEN (f.nu_ano - f.ano_nasc) < 60 THEN '50-59'
            WHEN (f.nu_ano - f.ano_nasc) < 70 THEN '60-69'
            ELSE '70+'
        END,
        f.evolucao, 'petequia_n', f.petequia_n
    FROM fato_dengue f

    UNION ALL
    SELECT
        CASE
            WHEN f.ano_nasc IS NULL THEN 'Não informado'
            WHEN f.ano_nasc < 1900 OR f.ano_nasc > f.nu_ano THEN 'Não informado'
            WHEN (f.nu_ano - f.ano_nasc) < 10 THEN '0-9'
            WHEN (f.nu_ano - f.ano_nasc) < 20 THEN '10-19'
            WHEN (f.nu_ano - f.ano_nasc) < 30 THEN '20-29'
            WHEN (f.nu_ano - f.ano_nasc) < 40 THEN '30-39'
            WHEN (f.nu_ano - f.ano_nasc) < 50 THEN '40-49'
            WHEN (f.nu_ano - f.ano_nasc) < 60 THEN '50-59'
            WHEN (f.nu_ano - f.ano_nasc) < 70 THEN '60-69'
            ELSE '70+'
        END,
        f.evolucao, 'leucopenia', f.leucopenia
    FROM fato_dengue f

    UNION ALL
    SELECT
        CASE
            WHEN f.ano_nasc IS NULL THEN 'Não informado'
            WHEN f.ano_nasc < 1900 OR f.ano_nasc > f.nu_ano THEN 'Não informado'
            WHEN (f.nu_ano - f.ano_nasc) < 10 THEN '0-9'
            WHEN (f.nu_ano - f.ano_nasc) < 20 THEN '10-19'
            WHEN (f.nu_ano - f.ano_nasc) < 30 THEN '20-29'
            WHEN (f.nu_ano - f.ano_nasc) < 40 THEN '30-39'
            WHEN (f.nu_ano - f.ano_nasc) < 50 THEN '40-49'
            WHEN (f.nu_ano - f.ano_nasc) < 60 THEN '50-59'
            WHEN (f.nu_ano - f.ano_nasc) < 70 THEN '60-69'
            ELSE '70+'
        END,
        f.evolucao, 'laco', f.laco
    FROM fato_dengue f

    UNION ALL
    SELECT
        CASE
            WHEN f.ano_nasc IS NULL THEN 'Não informado'
            WHEN f.ano_nasc < 1900 OR f.ano_nasc > f.nu_ano THEN 'Não informado'
            WHEN (f.nu_ano - f.ano_nasc) < 10 THEN '0-9'
            WHEN (f.nu_ano - f.ano_nasc) < 20 THEN '10-19'
            WHEN (f.nu_ano - f.ano_nasc) < 30 THEN '20-29'
            WHEN (f.nu_ano - f.ano_nasc) < 40 THEN '30-39'
            WHEN (f.nu_ano - f.ano_nasc) < 50 THEN '40-49'
            WHEN (f.nu_ano - f.ano_nasc) < 60 THEN '50-59'
            WHEN (f.nu_ano - f.ano_nasc) < 70 THEN '60-69'
            ELSE '70+'
        END,
        f.evolucao, 'dor_retro', f.dor_retro
    FROM fato_dengue f
)
SELECT
    faixa_etaria,
    sintoma,
    COUNT(*) FILTER (WHERE presente = 1) AS total_casos,
    SUM(CASE WHEN presente = 1 AND evolucao = 2 THEN 1 ELSE 0 END) AS total_obitos,
    ROUND(
        SUM(CASE WHEN presente = 1 AND evolucao = 2 THEN 1 ELSE 0 END)::numeric
        / NULLIF(COUNT(*) FILTER (WHERE presente = 1), 0),
        6
    ) AS taxa_letalidade
FROM sintomas_base
GROUP BY faixa_etaria, sintoma;

CREATE OR REPLACE VIEW vw_sintomas_sexo AS
WITH sintomas_base AS (
    SELECT v.cs_sexo, f.evolucao, 'mialgia' AS sintoma, f.mialgia AS presente
    FROM fato_dengue f
    LEFT JOIN dim_vitima v ON f.sk_vitima = v.sk_vitima

    UNION ALL
    SELECT v.cs_sexo, f.evolucao, 'cefaleia', f.cefaleia
    FROM fato_dengue f
    LEFT JOIN dim_vitima v ON f.sk_vitima = v.sk_vitima

    UNION ALL
    SELECT v.cs_sexo, f.evolucao, 'exantema', f.exantema
    FROM fato_dengue f
    LEFT JOIN dim_vitima v ON f.sk_vitima = v.sk_vitima

    UNION ALL
    SELECT v.cs_sexo, f.evolucao, 'vomito', f.vomito
    FROM fato_dengue f
    LEFT JOIN dim_vitima v ON f.sk_vitima = v.sk_vitima

    UNION ALL
    SELECT v.cs_sexo, f.evolucao, 'nausea', f.nausea
    FROM fato_dengue f
    LEFT JOIN dim_vitima v ON f.sk_vitima = v.sk_vitima

    UNION ALL
    SELECT v.cs_sexo, f.evolucao, 'dor_costas', f.dor_costas
    FROM fato_dengue f
    LEFT JOIN dim_vitima v ON f.sk_vitima = v.sk_vitima

    UNION ALL
    SELECT v.cs_sexo, f.evolucao, 'conjuntvit', f.conjuntvit
    FROM fato_dengue f
    LEFT JOIN dim_vitima v ON f.sk_vitima = v.sk_vitima

    UNION ALL
    SELECT v.cs_sexo, f.evolucao, 'artrite', f.artrite
    FROM fato_dengue f
    LEFT JOIN dim_vitima v ON f.sk_vitima = v.sk_vitima

    UNION ALL
    SELECT v.cs_sexo, f.evolucao, 'artralgia', f.artralgia
    FROM fato_dengue f
    LEFT JOIN dim_vitima v ON f.sk_vitima = v.sk_vitima

    UNION ALL
    SELECT v.cs_sexo, f.evolucao, 'petequia_n', f.petequia_n
    FROM fato_dengue f
    LEFT JOIN dim_vitima v ON f.sk_vitima = v.sk_vitima

    UNION ALL
    SELECT v.cs_sexo, f.evolucao, 'leucopenia', f.leucopenia
    FROM fato_dengue f
    LEFT JOIN dim_vitima v ON f.sk_vitima = v.sk_vitima

    UNION ALL
    SELECT v.cs_sexo, f.evolucao, 'laco', f.laco
    FROM fato_dengue f
    LEFT JOIN dim_vitima v ON f.sk_vitima = v.sk_vitima

    UNION ALL
    SELECT v.cs_sexo, f.evolucao, 'dor_retro', f.dor_retro
    FROM fato_dengue f
    LEFT JOIN dim_vitima v ON f.sk_vitima = v.sk_vitima
)
SELECT
    cs_sexo,
    sintoma,
    COUNT(*) FILTER (WHERE presente = 1) AS total_casos,
    SUM(CASE WHEN presente = 1 AND evolucao = 2 THEN 1 ELSE 0 END) AS total_obitos,
    ROUND(
        SUM(CASE WHEN presente = 1 AND evolucao = 2 THEN 1 ELSE 0 END)::numeric
        / NULLIF(COUNT(*) FILTER (WHERE presente = 1), 0),
        6
    ) AS taxa_letalidade
FROM sintomas_base
GROUP BY cs_sexo, sintoma;


CREATE OR REPLACE VIEW vw_sintomas_frequencia_final AS
SELECT
    cs_sexo,
    CASE sintoma
        WHEN 'cefaleia' THEN 'Cefaleia'
        WHEN 'mialgia' THEN 'Mialgia'
        WHEN 'nausea' THEN 'Náusea'
        WHEN 'vomito' THEN 'Vômito'
        WHEN 'dor_retro' THEN 'Dor Retro-orbitária'
        WHEN 'dor_costas' THEN 'Dor nas Costas'
        WHEN 'artralgia' THEN 'Artralgia'
        WHEN 'artrite' THEN 'Artrite'
        WHEN 'exantema' THEN 'Exantema'
        WHEN 'petequia_n' THEN 'Petéquias'
        WHEN 'leucopenia' THEN 'Leucopenia'
        WHEN 'laco' THEN 'Teste do Laço'
        WHEN 'conjuntvit' THEN 'Conjuntivite'
        ELSE sintoma
    END AS sintoma_nome,
    total_casos,
    total_obitos,
    taxa_letalidade
FROM vw_sintomas_sexo;